"""Windows one-shot Collector contracts, test double, and read-only Probe."""

from .allowlist import ProbeAllowlist
from .contracts import (
    ExternalSignatureStatus,
    ManifestSignatureProof,
    ManifestVerificationCode,
    ManifestVerificationContext,
    ManifestVerificationError,
    MockCollectionCode,
    MockCollectionError,
    MockCollectionRun,
    MockProbeResult,
    NonceStatus,
    ProbeContract,
    VerifiedExecutionPlan,
    VerifiedProbeRequest,
)
from .coverage import (
    CoverageContractError,
    CoverageSummary,
    verify_imp031_coverage,
)
from .expanded import (
    ADMINISTRATOR_PROBES,
    ADMINISTRATOR_SCRIPT_SHA256,
    STANDARD_NON_STORAGE_PROBES,
    STANDARD_SCRIPT_SHA256,
    ExpandedCollectionCode,
    ExpandedCollectionError,
    ExpandedProbeResult,
    ExpandedWindowsCollection,
    ExpandedWindowsCollector,
)
from .manifest import MAX_MANIFEST_BYTES, CollectorManifestVerifier
from .mock import MockCollector
from .process import (
    BoundedCommandResult,
    BoundedExecutionCode,
    BoundedExecutionError,
    BoundedProcessExecutor,
)
from .safety import (
    SAFETY_SNAPSHOT_SCRIPT_SHA256,
    CollectorSafetyCode,
    CollectorSafetyError,
    CollectorSafetyPolicy,
    ElevationNotice,
    PrivilegeLevel,
    PrivilegeSeparatedPlans,
    SafetySnapshot,
    SafetyVerifiedCollection,
    SafeWindowsCollectionCoordinator,
    WindowsSafetySnapshotter,
    authorize_elevated_plan,
    split_execution_plan,
)
from .windows import (
    WINDOWS_PROBE_SCRIPT_SHA256,
    CommandResult,
    WindowsCollectionCode,
    WindowsCollectionError,
    WindowsCollectionRun,
    WindowsExecutionContext,
    WindowsProbeResult,
    WindowsReadOnlyCollector,
)

__all__ = [
    "MAX_MANIFEST_BYTES",
    "CollectorManifestVerifier",
    "ExternalSignatureStatus",
    "ManifestSignatureProof",
    "ManifestVerificationCode",
    "ManifestVerificationContext",
    "ManifestVerificationError",
    "MockCollectionCode",
    "MockCollectionError",
    "MockCollectionRun",
    "MockCollector",
    "MockProbeResult",
    "NonceStatus",
    "ProbeAllowlist",
    "ProbeContract",
    "BoundedCommandResult",
    "BoundedExecutionCode",
    "BoundedExecutionError",
    "BoundedProcessExecutor",
    "CoverageContractError",
    "CoverageSummary",
    "verify_imp031_coverage",
    "ADMINISTRATOR_PROBES",
    "ADMINISTRATOR_SCRIPT_SHA256",
    "STANDARD_NON_STORAGE_PROBES",
    "STANDARD_SCRIPT_SHA256",
    "ExpandedCollectionCode",
    "ExpandedCollectionError",
    "ExpandedProbeResult",
    "ExpandedWindowsCollection",
    "ExpandedWindowsCollector",
    "SAFETY_SNAPSHOT_SCRIPT_SHA256",
    "CollectorSafetyCode",
    "CollectorSafetyError",
    "CollectorSafetyPolicy",
    "ElevationNotice",
    "PrivilegeLevel",
    "PrivilegeSeparatedPlans",
    "SafeWindowsCollectionCoordinator",
    "SafetySnapshot",
    "SafetyVerifiedCollection",
    "WindowsSafetySnapshotter",
    "authorize_elevated_plan",
    "split_execution_plan",
    "VerifiedExecutionPlan",
    "VerifiedProbeRequest",
    "WINDOWS_PROBE_SCRIPT_SHA256",
    "CommandResult",
    "WindowsCollectionCode",
    "WindowsCollectionError",
    "WindowsCollectionRun",
    "WindowsExecutionContext",
    "WindowsProbeResult",
    "WindowsReadOnlyCollector",
]
